name: Docker CI

on:
 push:
   branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest


   steps:
    - users: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

     - name: Build Docker image
       run: docker build -t arif346/cactros-flask-new .

     - name: Push Docker image
       run: docker push arif346/cactros-flask-new
